UAST: fix hadoop-client dep version
This is needed to avoid conflicts in guava version :/

 - Depending on the Spark version, it might bring hadoop-clinet compiled for pre guava v.19
 - bblfsh/client-scala though ScalaPB brings guava v.19

Otherwise, it results in runitme

```
java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V
 from class org.apache.hadoop.mapreduce.lib.input.FileInputFormat
```